const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const gl={VERTEX_SHADER:1,FRAGMENT_SHADER:2,COMPILE_STATUS:3,LINK_STATUS:4,ARRAY_BUFFER:5,STATIC_DRAW:6,FLOAT:7,TRIANGLES:8,TEXTURE0:100,TEXTURE_2D:101,RGBA:102,UNSIGNED_BYTE:103,TEXTURE_MIN_FILTER:104,TEXTURE_MAG_FILTER:105,TEXTURE_WRAP_S:106,TEXTURE_WRAP_T:107,LINEAR:108,CLAMP_TO_EDGE:109,UNPACK_FLIP_Y_WEBGL:110,COLOR_BUFFER_BIT:1,DEPTH_BUFFER_BIT:2,DEPTH_TEST:3,
  createShader:()=>({}),shaderSource(){},compileShader(){},getShaderParameter:()=>true,createProgram:()=>({}),attachShader(){},linkProgram(){},getProgramParameter:()=>true,createBuffer:()=>({}),bindBuffer(){},bufferData(_,v){assert(v instanceof Float32Array);},createTexture:()=>({}),activeTexture(){},bindTexture(){},texImage2D(){},texParameteri(){},pixelStorei(){},getAttribLocation:()=>0,getUniformLocation:()=>({}),useProgram(){},uniform1i(){},uniform2f(){},uniform1f(){},uniform3fv(_,v){assert.equal(v.length,3);},viewport(){},clearColor(){},clear(){},enable(){},enableVertexAttribArray(){},vertexAttribPointer(){},drawArrays(_,__,count){assert(count>1000);this.draws++;},draws:0};
const listeners={},canvas={width:0,height:0,getContext:()=>gl,getBoundingClientRect:()=>({left:0,top:0,width:800,height:600}),addEventListener(n,fn){listeners[n]=fn;},setPointerCapture(){}};
const painter={setTransform(){},clearRect(){},beginPath(){},arc(){},fill(){},stroke(){},fillText(){}};
const markers={width:0,height:0,getContext:()=>painter};
const ctx={window:{devicePixelRatio:1,addEventListener(){},matchMedia:()=>({matches:false})},Math,Date,Float32Array,Uint8Array,Image:class{set src(value){this.url=value;this.onload();}},requestAnimationFrame(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,"../www/globe.js"),"utf8"),ctx);
const math=ctx.window.SunflowerGlobeMath;
const noon=math.solarPosition(new Date("2026-03-20T12:00:00Z")),midnight=math.solarPosition(new Date("2026-03-20T00:00:00Z")),summer=math.solarPosition(new Date("2026-06-21T12:00:00Z"));
assert(Math.abs(noon[0])<2&&Math.abs(noon[1])<4);assert(Math.abs(midnight[1])>170);assert(summer[0]>22&&summer[0]<25);
assert(math.centroids.Armenia&&math.centroids.China);let chosen="";
const p={id:"caucasus-armenia-yerevan",city:"Yerevan",country:"Armenia",region:"Caucasus"};
const globe=new ctx.window.SunflowerGlobe(canvas,markers,{getPlaces:()=>[p],getVisited:()=>({}),onCountry:c=>chosen=c});globe.yaw=0;globe.pitch=0;globe.setActive(true);globe.draw();assert(gl.draws>0);const center=globe.project(0,0,800,600);assert(Math.abs(center.x-400)<1&&Math.abs(center.y-300)<1);globe.focus(40.2,44.5);globe.draw();assert(globe.hit.length>0);globe.pick(globe.hit[0].x,globe.hit[0].y);assert.equal(chosen,"Armenia");
globe.yaw=0;globe.pitch=0;listeners.pointerdown({pointerId:1,pointerType:"mouse",button:0,clientX:400,clientY:300});listeners.pointermove({pointerId:1,clientX:400,clientY:400});assert(globe.project(0,0,800,600).y>300,"downward drag moves the visible globe down");listeners.pointermove({pointerId:1,clientX:400,clientY:580});assert(globe.pitch>1.18,"downward mouse drag goes past the pole");listeners.pointermove({pointerId:1,clientX:400,clientY:300});assert(Math.abs(globe.project(0,0,800,600).y-300)<1,"dragging back up reverses the turn");listeners.pointerup({pointerId:1,clientX:400,clientY:300});
let prevented=0;for(let i=0;i<15;i++)listeners.wheel({deltaY:-120,preventDefault(){prevented++;}});assert.equal(prevented,15);assert(globe.distance>=1.12&&globe.distance<1.3,"wheel zoom gets close without crossing the near clipping plane");globe.zoom(.01);assert.equal(globe.distance,1.12);globe.zoom(100);assert.equal(globe.distance,6);
globe.distance=3.25;listeners.pointerdown({pointerId:2,pointerType:"touch",clientX:300,clientY:300});listeners.pointerdown({pointerId:3,pointerType:"touch",clientX:500,clientY:300});listeners.pointermove({pointerId:3,clientX:600,clientY:300});assert(globe.distance<3.25,"spreading fingers zooms closer");listeners.pointerup({pointerId:2,clientX:300,clientY:300});listeners.pointerup({pointerId:3,clientX:600,clientY:300});
console.log("Solar lighting, geographic markers, vertical drag and close zoom passed.");
